name: Generating ASCII
on: push
jobs:
    generate-ascii:
        runs-on: ubuntu-latest
        steps:
        - name: Update the repo
          run: sudo apt-get update && sudo apt-get install cowsay -y
        - name: Generate Dragon
          run: cowsay -f dragon "Hello From Dragon" > dragon.txt
        - name: Upload the artifact 
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text
            path: dragon.txt

    build_job_file-exist:
      needs: generate-ascii
      runs-on: ubuntu-latest
      steps:
      - name: Downloading the artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-text
      - name: Checking the file
        run: grep -i "dragon" dragon.txt

    build_job_file-content:
      needs: [generate-ascii,build_job_file-exist]
      runs-on: ubuntu-latest
      steps:
      - name: Downloading the artifact
        uses: actions/download-artifact@v4
        with:  
          name: dragon-text
      - name: check the content
        run: cat dragon.txt

